import React, { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { generateMarketingInsights, generateProductRecommendations } from '@/services/ai';
import { salesData, kpiData, inventoryData } from '@/data/mockData';
import { Sparkles, TrendingUp, Target, Loader2, AlertTriangle } from 'lucide-react';
import { useAI } from '@/contexts/AIContext';

export function AIInsightsPage() {
  const [insights, setInsights] = useState<any[]>([]);
  const [recommendations, setRecommendations] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const { isAIEnabled } = useAI();

  const fetchAI = async () => {
    if (!isAIEnabled) return;
    setIsLoading(true);
    try {
      const [aiInsights, aiRecs] = await Promise.all([
        generateMarketingInsights(salesData, kpiData),
        generateProductRecommendations(inventoryData)
      ]);
      setInsights(aiInsights);
      setRecommendations(aiRecs);
    } catch (error) {
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAI();
  }, [isAIEnabled]);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900 flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-blue-600" />
            AI-Powered Insights
          </h1>
          <p className="text-sm text-gray-500 mt-1">Predictions and analytics generated by Gemini AI.</p>
        </div>
        <Button onClick={fetchAI} disabled={isLoading || !isAIEnabled}>
          {isLoading ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Sparkles className="w-4 h-4 mr-2" />}
          Regenerate Insights
        </Button>
      </div>

      {!isAIEnabled ? (
        <Card>
          <CardContent className="h-64 flex flex-col items-center justify-center text-gray-500">
            <AlertTriangle className="w-12 h-12 mb-4 text-gray-300" />
            <p className="text-lg font-medium text-gray-900">AI is Disabled</p>
            <p className="text-sm">Please enable AI in the global toggle to generate insights.</p>
          </CardContent>
        </Card>
      ) : isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card className="h-64 flex items-center justify-center bg-gray-50/50">
            <Loader2 className="w-8 h-8 text-blue-600 animate-spin" />
          </Card>
          <Card className="h-64 flex items-center justify-center bg-gray-50/50">
            <Loader2 className="w-8 h-8 text-blue-600 animate-spin" />
          </Card>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Target className="w-5 h-5 text-indigo-600" />
                <CardTitle>Marketing Optimization</CardTitle>
              </div>
              <CardDescription>Actionable insights derived from your KPIs and recent trends.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {insights.length > 0 ? insights.map((insight, idx) => (
                  <div key={idx} className="p-4 rounded-xl border border-gray-100 bg-gray-50/50">
                    <div className="flex items-start justify-between mb-2">
                      <h4 className="font-semibold text-gray-900">{insight.title}</h4>
                      <Badge variant={
                        insight.impact === 'High' ? 'success' : 
                        insight.impact === 'Medium' ? 'warning' : 'outline'
                      }>
                        {insight.impact} Impact
                      </Badge>
                    </div>
                    <p className="text-sm text-gray-600 leading-relaxed">{insight.description}</p>
                  </div>
                )) : (
                  <p className="text-gray-500 text-sm">Failed to load insights. Please verify your Gemini API key.</p>
                )}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-green-600" />
                <CardTitle>Product Recommendations</CardTitle>
              </div>
              <CardDescription>AI-suggested products to feature in upcoming campaigns.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {recommendations.length > 0 ? recommendations.map((rec, idx) => (
                  <div key={idx} className="flex gap-4 p-4 rounded-xl border border-gray-100">
                    <div className="w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 font-bold shrink-0">
                      #{idx + 1}
                    </div>
                    <div>
                      <h4 className="font-semibold text-gray-900">{rec.productName}</h4>
                      <p className="text-sm text-gray-500 mt-1 leading-relaxed">{rec.rationale}</p>
                    </div>
                  </div>
                )) : (
                  <p className="text-gray-500 text-sm">Failed to load recommendations. Please verify your Gemini API key.</p>
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
